spring:
  application:
    name: im-distribute-server
  cloud:
    nacos:
      discovery:
        server-addr: 121.41.11.48:8848
        username: nacos
        password: nacos
        namespace: public

  datasource:
    url: jdbc:mysql://localhost:3308/im_system
    username: root
    password: root
  data:
    redis:
      host: 127.0.0.1
      port: 6379


